docs: presigned-url api 문서수정
team-ppeople/pp-oas-swagger pull request #17
Opened 2024-04-28 13:41 UTC by bulmandu

presigned-url API 

- payload 및 Response 변경

2024-04-29 08:47 UTC, LeeEunjeong1 approved these changes

2024-04-29 09:12 UTC, sinbom approved these changes

2024-04-30 00:23 UTC, jkim68888 approved these changes

2024-05-03 08:34 UTC, sinbom requested changes
@bulmandu 필드명 오타 발생한 부분은 수정이 필요할 것 같습니다~ 확인 부탁드려요 😉

2024-05-03 08:34 UTC, sinbom commented on swagger.yaml
> +                      - uploadFileType
@bulmandu 여기 필수 필드명에서 uploadFileTpye 필드가 properties에서는 fileType으로 정의되어 있어요!

2024-05-03 08:34 UTC, sinbom commented on swagger.yaml
> +                          - s3 객체 이름은 UUID로 업로드됩니다.
@bulmandu 요청시에 파일 이름을 UUID로 입력하면 되는건가요?
요청이랑 응답 예시 값이 전부 UUID 형태가 아닌 example1, example2로 되어 있습니다.

2024-05-05 15:47 UTC, bulmandu commented on swagger.yaml
> +                          - s3 객체 이름은 UUID로 업로드됩니다.
요청시에 받았던 파일이름과는 상관없이 UUID를 따로 생성해서 업로드합니다. 
요청했던 `fileName`이 각각 `presignedUploadUrl`와 `fileUrl`로 생성되었음을 구분할 용도로 다시 응답하고 있습니다.

2024-05-06 08:53 UTC, sinbom approved these changes

2024-05-06 08:53 UTC, merged